### GENERAL SETTINGS ###

# Site settings
title: VICKY GUARESCHI
description: "Portfolio of a 26 year old design, illustration and photopgraphy lover."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "http://www.vickyguareschi.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#606060" #"#F70031"
  primary_rgb: "96,96,96" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#fa789c" #"#6f6f6f"
  link: "#f5b7d4"
  link_hover: "#b64780"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: instagram
    url: http://instagram.com/vickyguareschi
  - title: github
    url: http://github.com/vickyguareschi
  - title: linkedin
    url: https://ar.linkedin.com/in/vickyguareschi

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: vickyguareschi@gmail.com
tel: 

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I'm a 26 year old who loves design, photography and illustration. Just a geeky girl who wants to create pretty designs for the world, learning as much as I can in the process."
